/* Auto-generated by genmsg_cpp for file /home/mingfeng/ros_workspace/quadrotor_msgs/msg/ControlInputs.msg */
#ifndef QUADROTOR_MSGS_MESSAGE_CONTROLINPUTS_H
#define QUADROTOR_MSGS_MESSAGE_CONTROLINPUTS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct ControlInputs_ {
  typedef ControlInputs_<ContainerAllocator> Type;

  ControlInputs_()
  : header()
  , scaledInputs()
  , zigbeeInputs()
  {
    scaledInputs.assign(0);
    zigbeeInputs.assign(0);
  }

  ControlInputs_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , scaledInputs()
  , zigbeeInputs()
  {
    scaledInputs.assign(0);
    zigbeeInputs.assign(0);
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef boost::array<int16_t, 16>  _scaledInputs_type;
  boost::array<int16_t, 16>  scaledInputs;

  typedef boost::array<int16_t, 16>  _zigbeeInputs_type;
  boost::array<int16_t, 16>  zigbeeInputs;


  typedef boost::shared_ptr< ::quadrotor_msgs::ControlInputs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::ControlInputs_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ControlInputs
typedef  ::quadrotor_msgs::ControlInputs_<std::allocator<void> > ControlInputs;

typedef boost::shared_ptr< ::quadrotor_msgs::ControlInputs> ControlInputsPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::ControlInputs const> ControlInputsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::quadrotor_msgs::ControlInputs_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::quadrotor_msgs::ControlInputs_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quadrotor_msgs::ControlInputs_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quadrotor_msgs::ControlInputs_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::ControlInputs_<ContainerAllocator> > {
  static const char* value() 
  {
    return "37612a0241cc186045688e2e42377320";
  }

  static const char* value(const  ::quadrotor_msgs::ControlInputs_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x37612a0241cc1860ULL;
  static const uint64_t static_value2 = 0x45688e2e42377320ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::ControlInputs_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quadrotor_msgs/ControlInputs";
  }

  static const char* value(const  ::quadrotor_msgs::ControlInputs_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::ControlInputs_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int16[16] scaledInputs\n\
int16[16] zigbeeInputs\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::quadrotor_msgs::ControlInputs_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::quadrotor_msgs::ControlInputs_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::quadrotor_msgs::ControlInputs_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::ControlInputs_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.scaledInputs);
    stream.next(m.zigbeeInputs);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ControlInputs_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::ControlInputs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::quadrotor_msgs::ControlInputs_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "scaledInputs[]" << std::endl;
    for (size_t i = 0; i < v.scaledInputs.size(); ++i)
    {
      s << indent << "  scaledInputs[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.scaledInputs[i]);
    }
    s << indent << "zigbeeInputs[]" << std::endl;
    for (size_t i = 0; i < v.zigbeeInputs.size(); ++i)
    {
      s << indent << "  zigbeeInputs[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.zigbeeInputs[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_CONTROLINPUTS_H

