/* Auto-generated by genmsg_cpp for file /home/mingfeng/ros_workspace/quadrotor_msgs/msg/ControlWarn.msg */
#ifndef QUADROTOR_MSGS_MESSAGE_CONTROLWARN_H
#define QUADROTOR_MSGS_MESSAGE_CONTROLWARN_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct ControlWarn_ {
  typedef ControlWarn_<ContainerAllocator> Type;

  ControlWarn_()
  : header()
  , warnName()
  , warnInfo(0.0)
  {
  }

  ControlWarn_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , warnName(_alloc)
  , warnInfo(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _warnName_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  warnName;

  typedef double _warnInfo_type;
  double warnInfo;


  typedef boost::shared_ptr< ::quadrotor_msgs::ControlWarn_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::ControlWarn_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ControlWarn
typedef  ::quadrotor_msgs::ControlWarn_<std::allocator<void> > ControlWarn;

typedef boost::shared_ptr< ::quadrotor_msgs::ControlWarn> ControlWarnPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::ControlWarn const> ControlWarnConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::quadrotor_msgs::ControlWarn_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::quadrotor_msgs::ControlWarn_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quadrotor_msgs::ControlWarn_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quadrotor_msgs::ControlWarn_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::ControlWarn_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c5676241895812ed60a907c0d50bb0fd";
  }

  static const char* value(const  ::quadrotor_msgs::ControlWarn_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc5676241895812edULL;
  static const uint64_t static_value2 = 0x60a907c0d50bb0fdULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::ControlWarn_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quadrotor_msgs/ControlWarn";
  }

  static const char* value(const  ::quadrotor_msgs::ControlWarn_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::ControlWarn_<ContainerAllocator> > {
  static const char* value() 
  {
    return "std_msgs/Header header\n\
string warnName\n\
float64 warnInfo\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::quadrotor_msgs::ControlWarn_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::quadrotor_msgs::ControlWarn_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::quadrotor_msgs::ControlWarn_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::ControlWarn_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.warnName);
    stream.next(m.warnInfo);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ControlWarn_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::ControlWarn_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::quadrotor_msgs::ControlWarn_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "warnName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.warnName);
    s << indent << "warnInfo: ";
    Printer<double>::stream(s, indent + "  ", v.warnInfo);
  }
};


} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_CONTROLWARN_H

