/* Auto-generated by genmsg_cpp for file /home/mingfeng/ros_workspace/quadrotor_msgs/msg/DirectionWithCovarianceStamped.msg */
#ifndef QUADROTOR_MSGS_MESSAGE_DIRECTIONWITHCOVARIANCESTAMPED_H
#define QUADROTOR_MSGS_MESSAGE_DIRECTIONWITHCOVARIANCESTAMPED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Point.h"
#include "geometry_msgs/Point.h"

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct DirectionWithCovarianceStamped_ {
  typedef DirectionWithCovarianceStamped_<ContainerAllocator> Type;

  DirectionWithCovarianceStamped_()
  : header()
  , direction()
  , reference()
  , covariance()
  {
    covariance.assign(0.0);
  }

  DirectionWithCovarianceStamped_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , direction(_alloc)
  , reference(_alloc)
  , covariance()
  {
    covariance.assign(0.0);
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _direction_type;
   ::geometry_msgs::Point_<ContainerAllocator>  direction;

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _reference_type;
   ::geometry_msgs::Point_<ContainerAllocator>  reference;

  typedef boost::array<double, 9>  _covariance_type;
  boost::array<double, 9>  covariance;


  typedef boost::shared_ptr< ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct DirectionWithCovarianceStamped
typedef  ::quadrotor_msgs::DirectionWithCovarianceStamped_<std::allocator<void> > DirectionWithCovarianceStamped;

typedef boost::shared_ptr< ::quadrotor_msgs::DirectionWithCovarianceStamped> DirectionWithCovarianceStampedPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::DirectionWithCovarianceStamped const> DirectionWithCovarianceStampedConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d37b3fe7415987ab30cd40f3030fc2e2";
  }

  static const char* value(const  ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd37b3fe7415987abULL;
  static const uint64_t static_value2 = 0x30cd40f3030fc2e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quadrotor_msgs/DirectionWithCovarianceStamped";
  }

  static const char* value(const  ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
geometry_msgs/Point direction\n\
geometry_msgs/Point reference\n\
float64[9] covariance\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.direction);
    stream.next(m.reference);
    stream.next(m.covariance);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct DirectionWithCovarianceStamped_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::quadrotor_msgs::DirectionWithCovarianceStamped_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "direction: ";
s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.direction);
    s << indent << "reference: ";
s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.reference);
    s << indent << "covariance[]" << std::endl;
    for (size_t i = 0; i < v.covariance.size(); ++i)
    {
      s << indent << "  covariance[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.covariance[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_DIRECTIONWITHCOVARIANCESTAMPED_H

