/* Auto-generated by genmsg_cpp for file /home/mingfeng/ros_workspace/quadrotor_msgs/msg/HeightStamped.msg */
#ifndef QUADROTOR_MSGS_MESSAGE_HEIGHTSTAMPED_H
#define QUADROTOR_MSGS_MESSAGE_HEIGHTSTAMPED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct HeightStamped_ {
  typedef HeightStamped_<ContainerAllocator> Type;

  HeightStamped_()
  : header()
  , height(0.0)
  {
  }

  HeightStamped_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , height(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _height_type;
  double height;


  typedef boost::shared_ptr< ::quadrotor_msgs::HeightStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::HeightStamped_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct HeightStamped
typedef  ::quadrotor_msgs::HeightStamped_<std::allocator<void> > HeightStamped;

typedef boost::shared_ptr< ::quadrotor_msgs::HeightStamped> HeightStampedPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::HeightStamped const> HeightStampedConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::quadrotor_msgs::HeightStamped_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::quadrotor_msgs::HeightStamped_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quadrotor_msgs::HeightStamped_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quadrotor_msgs::HeightStamped_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::HeightStamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "1b96bb17a3786a696442a57cb0232657";
  }

  static const char* value(const  ::quadrotor_msgs::HeightStamped_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x1b96bb17a3786a69ULL;
  static const uint64_t static_value2 = 0x6442a57cb0232657ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::HeightStamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quadrotor_msgs/HeightStamped";
  }

  static const char* value(const  ::quadrotor_msgs::HeightStamped_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::HeightStamped_<ContainerAllocator> > {
  static const char* value() 
  {
    return "std_msgs/Header header\n\
float64 height\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::quadrotor_msgs::HeightStamped_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::quadrotor_msgs::HeightStamped_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::quadrotor_msgs::HeightStamped_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::HeightStamped_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.height);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct HeightStamped_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::HeightStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::quadrotor_msgs::HeightStamped_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};


} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_HEIGHTSTAMPED_H

