/* Auto-generated by genmsg_cpp for file /home/mingfeng/ros_workspace/quadrotor_msgs/msg/RadioControl.msg */
#ifndef QUADROTOR_MSGS_MESSAGE_RADIOCONTROL_H
#define QUADROTOR_MSGS_MESSAGE_RADIOCONTROL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace quadrotor_msgs
{
template <class ContainerAllocator>
struct RadioControl_ {
  typedef RadioControl_<ContainerAllocator> Type;

  RadioControl_()
  : header()
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , throttle(0.0)
  , flap(0)
  , gear(0)
  {
  }

  RadioControl_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , roll(0.0)
  , pitch(0.0)
  , yaw(0.0)
  , throttle(0.0)
  , flap(0)
  , gear(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef double _roll_type;
  double roll;

  typedef double _pitch_type;
  double pitch;

  typedef double _yaw_type;
  double yaw;

  typedef double _throttle_type;
  double throttle;

  typedef int8_t _flap_type;
  int8_t flap;

  typedef int8_t _gear_type;
  int8_t gear;


  typedef boost::shared_ptr< ::quadrotor_msgs::RadioControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quadrotor_msgs::RadioControl_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct RadioControl
typedef  ::quadrotor_msgs::RadioControl_<std::allocator<void> > RadioControl;

typedef boost::shared_ptr< ::quadrotor_msgs::RadioControl> RadioControlPtr;
typedef boost::shared_ptr< ::quadrotor_msgs::RadioControl const> RadioControlConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::quadrotor_msgs::RadioControl_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::quadrotor_msgs::RadioControl_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace quadrotor_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::quadrotor_msgs::RadioControl_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::quadrotor_msgs::RadioControl_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::quadrotor_msgs::RadioControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "741fae7ca29c727eae807cac417216c8";
  }

  static const char* value(const  ::quadrotor_msgs::RadioControl_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x741fae7ca29c727eULL;
  static const uint64_t static_value2 = 0xae807cac417216c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::quadrotor_msgs::RadioControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "quadrotor_msgs/RadioControl";
  }

  static const char* value(const  ::quadrotor_msgs::RadioControl_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::quadrotor_msgs::RadioControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "std_msgs/Header header\n\
float64 roll\n\
float64 pitch\n\
float64 yaw\n\
float64 throttle\n\
int8 flap\n\
int8 gear\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::quadrotor_msgs::RadioControl_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::quadrotor_msgs::RadioControl_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::quadrotor_msgs::RadioControl_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::quadrotor_msgs::RadioControl_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.roll);
    stream.next(m.pitch);
    stream.next(m.yaw);
    stream.next(m.throttle);
    stream.next(m.flap);
    stream.next(m.gear);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct RadioControl_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quadrotor_msgs::RadioControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::quadrotor_msgs::RadioControl_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "throttle: ";
    Printer<double>::stream(s, indent + "  ", v.throttle);
    s << indent << "flap: ";
    Printer<int8_t>::stream(s, indent + "  ", v.flap);
    s << indent << "gear: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gear);
  }
};


} // namespace message_operations
} // namespace ros

#endif // QUADROTOR_MSGS_MESSAGE_RADIOCONTROL_H

