(cl:defpackage quadrotor_input-srv
  (:use )
  (:export
   "SELECTSTATESOURCE"
   "<SELECTSTATESOURCE-REQUEST>"
   "SELECTSTATESOURCE-REQUEST"
   "<SELECTSTATESOURCE-RESPONSE>"
   "SELECTSTATESOURCE-RESPONSE"
   "NOTIFYCONTROLLER"
   "<NOTIFYCONTROLLER-REQUEST>"
   "NOTIFYCONTROLLER-REQUEST"
   "<NOTIFYCONTROLLER-RESPONSE>"
   "NOTIFYCONTROLLER-RESPONSE"
   "COMMANDCONTROLLER"
   "<COMMANDCONTROLLER-REQUEST>"
   "COMMANDCONTROLLER-REQUEST"
   "<COMMANDCONTROLLER-RESPONSE>"
   "COMMANDCONTROLLER-RESPONSE"
  ))

