(cl:in-package quadrotor_msgs-msg)
(cl:export '(BASE_THROTTLE-VAL
          BASE_THROTTLE
          SCALE-VAL
          SCALE
          VOLTAGE-VAL
          VOLTAGE
          XY_ERROR-VAL
          XY_ERROR
          VX_ERROR-VAL
          VX_ERROR
          VY_ERROR-VAL
          VY_ERROR
          Z_ERROR-VAL
          Z_ERROR
          VZ_ERROR-VAL
          VZ_ERROR
          YAW_ERROR-VAL
          YAW_ERROR
          DESIRED_XYZ_YAW-VAL
          DESIRED_XYZ_YAW
          CURRENT_XYZ_YAW-VAL
          CURRENT_XYZ_YAW
          DESIRED_VELOCITY-VAL
          DESIRED_VELOCITY
          DESIRED_ACCELERATION-VAL
          DESIRED_ACCELERATION
          CMD-VAL
          CMD
          CMD_LIMITED-VAL
          CMD_LIMITED
))