"""autogenerated by genpy from quadrotor_msgs/StateDebug.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class StateDebug(genpy.Message):
  _md5sum = "4036a591967e8dadfb66a9590c8f625e"
  _type = "quadrotor_msgs/StateDebug"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Vector3 attitude
geometry_msgs/Vector3 attitude_desired

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 

float64 x
float64 y
float64 z
"""
  __slots__ = ['attitude','attitude_desired']
  _slot_types = ['geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       attitude,attitude_desired

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StateDebug, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.attitude is None:
        self.attitude = geometry_msgs.msg.Vector3()
      if self.attitude_desired is None:
        self.attitude_desired = geometry_msgs.msg.Vector3()
    else:
      self.attitude = geometry_msgs.msg.Vector3()
      self.attitude_desired = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.attitude.x, _x.attitude.y, _x.attitude.z, _x.attitude_desired.x, _x.attitude_desired.y, _x.attitude_desired.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.attitude is None:
        self.attitude = geometry_msgs.msg.Vector3()
      if self.attitude_desired is None:
        self.attitude_desired = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.attitude.x, _x.attitude.y, _x.attitude.z, _x.attitude_desired.x, _x.attitude_desired.y, _x.attitude_desired.z,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_6d.pack(_x.attitude.x, _x.attitude.y, _x.attitude.z, _x.attitude_desired.x, _x.attitude_desired.y, _x.attitude_desired.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.attitude is None:
        self.attitude = geometry_msgs.msg.Vector3()
      if self.attitude_desired is None:
        self.attitude_desired = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.attitude.x, _x.attitude.y, _x.attitude.z, _x.attitude_desired.x, _x.attitude_desired.y, _x.attitude_desired.z,) = _struct_6d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_6d = struct.Struct("<6d")
